name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build frontend
        run: |
          cd frontend
          yarn install
          yarn build
          mkdir ../client
          cp -r dist/* ../client
          cd ..
          rm -rf frontend
      - name: regroup sources
        run: |
          mv backend/* .
          rm -rf backend/
          rm .gitignore
      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ USER_NAME }}
          author_email: ${{ USER_EMAIL }}
          message: Build ✨
      - name: checkout to build branch
        run: |
          git push origin --delete build
          git checkout -b build
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          branch: build