name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build frontend
        run: |
          cd frontend
          yarn install
          yarn build
          mkdir ../client
          cp -r dist/* ../client
          cd ..
          rm -rf frontend
      - name: regroup sources
        run: |
          mv backend/* .
          rm -rf backend/
          rm .gitignore
      - name: commit changes
        run: |
          git config --global --add safe.directory $(pwd)
          git config --local user.name ${{ secrets.USER_NAME }}
          git config --local user.email ${{ secrets.USER_EMAIL }}
          git commit -am "Build ✨"
      - name: checkout to build branch
        run: |
          git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ secrets.USER_NAME }}/${{ github.event.repository.name }}.git
          git push origin --delete build
          git checkout -b build
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: build
