name: Deploy to EC2

on:
  push:
    branches:
      - preview
  pull_request: 
    branches: 
      - preview

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout prebuilt code
        uses: actions/checkout@v3
      - name: deploy
        run: |
          sudo docker compose down
          sudo docker compose up -d
