name: Hello world workflow

on:
  push:
    branches:
      - test-deployment

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: hello world
        run: echo "hello world"

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: saying goodbye
        run: echo "goodbye world"
